apiVersion: v2
appVersion: 1.27.1
name: cloudnative-pg
description: A Giant Swarm app for deploying CloudNative PostgreSQL.
home: https://github.com/giantswarm/cloudnative-pg-app
icon: https://s.giantswarm.io/app-icons/cloudnative-pg/icon-light.svg
sources:
  - https://github.com/cloudnative-pg/charts
version: 0.0.13
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.1
